title:            GektorGrom's Blog
description:      Жизнь в Канаде.
disqus_shortname: lion58
# url:              http://jesse.co.ua

# Owner/author information
owner:
  name:           Slava Mednikov
  avatar:         10738_10203285889011431_1473477160_n.jpg
  bio:            "Недавно переехал в Канаду по рабочей визе. Работаю на Olymel. Развлекаюсь этим бложиком"
  email:          gektorgrom@gmail.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:        lion58
  facebook:       slava.mednikov
  github:         
  stackexchange:  
  linkedin:       
  instagram:     gektorgrom 
  lastfm:        
  flickr:         
  tumblr:         
  hmfaysalsocial:   
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    

# Analytics and webmaster tools stuff goes here
google_analytics:   UA-48810704-1
google_verify:      uBF3ei3WP79pvyHbFhul0LDixl63SHSMZkDaMUjMctk
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# Links to include in top navigation
# For external links add external: true
links:
  - title: Домой
    url: /
  - title: Обо мне
    url: /about/
  - title: Статьи
    url: /articles/
  - title: Setup
    url: /theme-setup/
    external: true
  - title: FAQ
    url: /faq

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Edmonton
future:      true
pygments:    true
markdown:    kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

destination: ~/jekyll-sites/MyBlog/gektorgrom.github.io/
gems: ["emoji_for_jekyll"]
include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]